export const ADD_LOAN_LOCAL = 'ADD_LOAN_LOCAL';
export const DELETE_LOAN_LOCAL = 'DELETE_LOAN_LOCAL';
export const EDIT_LOAN_LOCAL = 'EDIT_LOAN_LOCAL';

export const SUBMIT_LOANS_REMOTE_SUCCESS = 'SUBMIT_LOANS_REMOTE_SUCCESS';
export const SUBMIT_LOANS_REMOTE_FAILURE = 'SUBMIT_LOANS_REMOTE_FAILURE';

export const ADD_LOAN_REMOTE_SUCCESS = 'ADD_LOAN_REMOTE_SUCCESS';
export const ADD_LOAN_REMOTE_FAILURE = 'ADD_LOAN_REMOTE_FAILURE';

export const DELETE_LOAN_REMOTE_SUCCESS = 'DELETE_LOAN_REMOTE_SUCCESS';
export const DELETE_LOAN_REMOTE_FAILURE = 'DELETE_LOAN_REMOTE_FAILURE';

export const EDIT_LOAN_REMOTE_SUCCESS = 'EDIT_LOAN_REMOTE_SUCCESS';
export const EDIT_LOAN_REMOTE_FAILURE = 'EDIT_LOAN_REMOTE_FAILURE';

export const UPLOAD_FEDERAL_SUCCESS = 'UPLOAD_FEDERAL_SUCCESS';
export const UPLOAD_FEDERAL_FAILURE = 'UPLOAD_FEDERAL_FAILURE';

export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SURVEY_SUBMIT = 'SURVEY_SUBMIT';
export const SURVEY_SUBMIT_SUCCESS = 'SURVEY_SUBMIT_SUCCESS';
export const SURVEY_SUBMIT_FAILURE = 'SURVEY_SUBMIT_FAILURE';

export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE';